### ISSUE TITLE
Use deprecated `get_attribute`, `set_attribute` instead of PlayerMetaRef

### ISSUE THREAD

**Issue by AFCMS** [APercy/airutils#1]
https://github.com/APercy/airutils/blob/66a9e916b0057b507bf7d9e3cb2c920e673ca13c/pilot_skin_manager.lua#L41-L45
https://github.com/APercy/airutils/blob/66a9e916b0057b507bf7d9e3cb2c920e673ca13c/pilot_skin_manager.lua#L71-L73
https://github.com/APercy/airutils/blob/66a9e916b0057b507bf7d9e3cb2c920e673ca13c/pilot_skin_manager.lua#L98-L99
(maybe more)

https://github.com/minetest/minetest/blob/34f15259fa5546dc9abaf974ca5385c276443697/doc/lua_api.txt#L7004-L7012

It raises warnings in the server console which is annoying sometimes.

**Comment by APercy** [comment]
Okay! Thank you :)
Fixed now
