### ISSUE TITLE
Skins not available in the inventory tab

### ISSUE THREAD

**Issue by dacmot** [APercy/airutils#2]
I tried a new MTG game with just SkinsDB and airutils, and could not see how to use the skins. Only the default skins were shown in the Skins tab (sam, castaways, farmers, princes(s) and rogues).

**Comment by dacmot** [comment]
Oh. I just noticed the command `/au_uniform`. Would it then be possible to simply add them to the Skins tab?

**Comment by bell07** [comment]
The mod does not have own skins, just existing skins enhancement. Therefore there is nothing to add to skins tab.
